name: Bump Package Version On Merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
jobs:
  bump-package-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bump package version
        run: |
          cd apps
          # Increment the version in package.json
           pr_title="${{ github.event.pull_request.title }}"
          echo $pr_title
          if [[ $pr_title == feat/* ]]; then
            echo "PR starts with 'feat': Do something"
            npm version major 
          elif [[ $pr_title == fix/* ]]; then
            npm version minor 
          elif [[ $pr_title == chore/* ]]; then
            npm version patch 
          else
            npm version patch 
          # Commit the updated package.json
          echo 2222222222222222222222
          sleep 50 
          cd ..
          git config user.name "Ehsan.Aj"
          git config user.email "eng.ahanj@gmail.com"
          git add apps/package.json
          git commit -m "Bump package version"
          # Push the changes back to the repo
          echo 333333333333333333
          echo ${{ secrets.GITHUB_TOKEN }}
          sleep 50 
          git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
