name: Bump Package Version On Merge

permissions:
  contents: write

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main
jobs:
  bump-package-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Bump package version
        run: |
          # Increment the version in package.json
           pr_title="${{ github.event.pull_request.title }}"
          echo $pr_title
          cd apps/
          if [[ $pr_title =~ ^(feat|Feat).* ]]; then
            echo "PR starts with 'feat':"
            npm version major 
          elif [[ ${pr_title,,} == fix/* ]]; then
            echo "PR starts with 'fix':"
            npm version minor 
          elif [[ ${pr_title,,} == chore/* ]]; then
            echo "PR starts with 'chore':"
            npm version patch 
          else
            npm version patch 
            fi
          NEW_VERSION=$(node -p "require('./package.json').version")
          # Commit the updated package.json
          cd ..
          git config user.name "Ehsan.Aj"
          git config user.email "eng.ahanj@gmail.com"
          git add apps/package.json
          git log --oneline
          git tag $NEW_VERSION
          git tag 
          git commit -m "Bump package version"
          git push && git push --tags
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
